palette = "tokyonight"

format = """
[](fg:bg)\
$os\
[](fg:bg bg:blue)\
$directory\
[](fg:blue bg:green)\
$git_branch\
$git_status\
[](fg:green)\
$fill\
[](fg:dark3)\
$nodejs\
$rust\
$elixir\
$python\
[](fg:bg_highlight bg:dark3)\
$cmd_duration\
[](fg:bg bg:bg_highlight)\
$time\
[](fg:bg)\
\n$character"""

[palettes.tokyonight]
bg_dark = "#1a1b26"
bg = "#24283b"
bg_highlight = "#292e42"
dark3 = "#414868"
fg = "#c0caf5"
fg_dark = "#a9b1d6"
blue = "#7aa2f7"
cyan = "#7dcfff"
green = "#9ece6a"
magenta = "#bb9af7"
red = "#f7768e"
yellow = "#e0af68"

[os]
disabled = false
style = "fg:blue bg:bg"
format = "[  $symbol  ]($style)"

[os.symbols]
Macos = ""
Linux = "🐧"
Windows = ""

[directory]
style = "fg:bg_dark bg:blue bold"
format = "[ $path ]($style)"
truncation_length = 0
fish_style_pwd_dir_length = 1

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "fg:bg_dark bg:green"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "fg:bg_dark bg:green"
format = "[(| $conflicted$stashed$deleted$renamed$modified$staged$untracked$ahead_behind )]($style)"
conflicted = "=${count} "
stashed = "📦${count} "
deleted = "✘${count} "
renamed = "»${count} "
modified = "!${count} "
staged = "+${count} "
untracked = "?${count} "
ahead = "⇡${count} "
behind = "⇣${count} "

[fill]
symbol = "─"
style = "fg:bg_highlight"

[nodejs]
symbol = ""
style = "fg:cyan bg:dark3"
format = "[ $symbol $version ]($style)"

[rust]
symbol = ""
style = "fg:red bg:dark3"
format = "[ $symbol $version ]($style)"

[elixir]
symbol = ""
style = "fg:magenta bg:dark3"
format = "[ $symbol $version ]($style)"

[python]
symbol = ""
style = "fg:cyan bg:dark3"
format = "[ $symbol $version ]($style)"

[cmd_duration]
min_time = 2_000
style = "fg:yellow bg:bg_highlight"
format = "[ 󱎫 $duration ]($style)"

[time]
disabled = false
time_format = "%R"
style = "fg:fg_dark bg:bg"
format = "[  $time ]($style)"

[character]
success_symbol = "[❯](bold fg:green)"
error_symbol = "[❯](bold fg:red)"
